### ISSUE TITLE
Theft check

### ISSUE THREAD

**Issue by mmahmud97** [Jordan-Sun/WashULostNFound#14]
How will you prevent this from becoming a free n for sale lol? 
- Similar to two people making claim for same article
- Maybe have the person that found it create 2 or 3 questions about the article that the person picking up has to answer to retrieve it
- Adding questions would be similar to the password safety questions about the article
- Simple to add but what if actual owner cant answer the questions lol 
- will have to solve this somehow

**Comment by Jordan-Sun** [comment]
Second point is something we can actually do. Someone add that to the project board.
This will be added to questions.
We need to talk about this next meeting before actually implementing it.

**Comment by Jordan-Sun** [comment]
This is the main issue for resolving conflicting claims.

**Comment by Jordan-Sun** [comment]
Added to prototype, need improvement.
